language: node_js
node_js:
  - "10"
addons:
    code_climate:
        repo_token: <supersecrettoken>
script: 
- npm run test
before_script:
- npm install codeclimate-test-reporter istanbul -g
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
after_success:
- npm run coveralls
- codeclimate-test-reporter < coverage/lcov.info